# 1.创建EFK命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: kube-efk-ns
---
# 2.创建服务账号
apiVersion: v1
kind: ServiceAccount
metadata:
  # 指定账号名称
  name: kube-efk-sa
  # 绑定命名空间
  namespace: kube-efk-ns
  labels:
    k8s-app: kube-efk
---
# 3.创建集群角色
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # 指定角色名称
  name: kube-efk-role
  labels:
    k8s-app: kube-efk
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "namespaces"
      - "endpoints"
    verbs:
      - "get"
---
# 4.集群角色绑定
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # 指定角色绑定名称
  name: kube-efk-rolebind
  # 绑定命名空间
  namespace: kube-efk-ns
  labels:
    k8s-app: kube-efk
# 绑定的服务账号
subjects:
  - kind: ServiceAccount
    name: kube-efk-sa
    namespace: kube-efk-ns
    apiGroup: ""
# 绑定的角色
roleRef:
  kind: ClusterRole
  name: kube-efk-role
  apiGroup: ""